### ISSUE TITLE
Outdated Documentation `JSON Web Token Options`

### ISSUE THREAD

**Issue by YLcoding** [nextauthjs/docs#4] opened 2021-09-02 21:08 UTC
Referring to: https://next-auth.js.org/configuration/options#json-web-token-options

In the above example, the jwt key field `signingKey` has changed to only accepting string.

In the docs:
```
jwt: {
  // wrong format
  signingKey: {
     kty: "oct",
     kid: "Dl893BEV-iVE-x9EC52TDmlJUgGm9oZ99_ZL025Hc5Q",
     alg: "HS512",
     k: "K7QqRmJOKRK2qcCKV_pi9PSBv3XP0fpTu30TP8xn4w01xR3ZMZM38yL2DnTVPVw6e4yhdh0jtoah-i4c_pZagA"
  },
  ...
}
```

Actually type:
```
jwt: {
  // correct format
  signingKey: "string",
  ...
}
```

More reference to the `JWTOptions` Type: https://github.com/nextauthjs/next-auth/blob/e8a58a01b6b8c456268771f9b382fa300ccab8ac/types/jwt.d.ts#L60

**Comment by balazsorban44** [comment] 2021-09-02 21:18
Duplicate of #5

**Closed by balazsorban44** 2021-09-02 21:18 UTC
